<a href="https://colab.research.google.com/github/Appy111/Python-Programming/blob/main/dada_a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a,b,c=10,20,30
print(a+b+c)

60


In [ ]:
a=b=c=d=10
print(a+b+c+d)

40


In [ ]:
a=40
print(a)
a=50
print(a)

40
50


In [ ]:
a=20
print(type(a))

<class 'int'>


In [ ]:
a='Apurvi'
print(a[2])

u


In [ ]:
a='Apurvi'
for b in a:
  print(b)

A
p
u
r
v
i


In [ ]:
a='Apurvi'
b=0
while b<(len(a)):
  print(a[b])
  b=b+1

A
p
u
r
v
i


In [ ]:
a=[]
print(a)

[]


In [ ]:
a=[1,2,3]
print(a)

[1, 2, 3]


In [ ]:
r=range(0,100)
l=list(r)
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [ ]:
a=[10,20,30]
print(a)
a=[100,20,30]
print(a)

[10, 20, 30]
[100, 20, 30]


In [ ]:
print(a[0])

100


In [ ]:
print(l[::2])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [ ]:
for i in l:
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [ ]:
a=range(0,11,2)
i=0
while i<len(a):
  print(a[i])
  i=i+1

0
2
4
6
8
10


In [ ]:
l=list(range(0,31,3))
print(l)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30]


In [ ]:
print(len(l))

11


In [ ]:
print(l.count(12))

1


In [ ]:
l.append(list(range(31,61,3)))
print(l)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, range(31, 61, 3), [31, 34, 37, 40, 43, 46, 49, 52, 55, 58]]


In [ ]:
b=list(range(31,61,3))
print(b)

[31, 34, 37, 40, 43, 46, 49, 52, 55, 58]


In [ ]:
l.append(b)
print(l)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, range(31, 61, 3), [31, 34, 37, 40, 43, 46, 49, 52, 55, 58], [31, 34, 37, 40, 43, 46, 49, 52, 55, 58], [31, 34, 37, 40, 43, 46, 49, 52, 55, 58], [31, 34, 37, 40, 43, 46, 49, 52, 55, 58], [31, 34, 37, 40, 43, 46, 49, 52, 55, 58], [31, 34, 37, 40, 43, 46, 49, 52, 55, 58]]


In [ ]:
a=list(range(0,41,4))
print(a)

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40]


In [ ]:
b=list(range(40,81,4))
print(b)

[40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80]


In [ ]:
a.append(b)
print(a)

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, [40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80]]


In [ ]:
a=[1,2,3]
a.insert(0,0)
a.insert(7,4)
print(a)

[0, 1, 2, 3, 4]


In [ ]:
b=list(range(44,81,4))
print(b)

[44, 48, 52, 56, 60, 64, 68, 72, 76, 80]


In [ ]:
a=list(range(0,41,4))
print(a)

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40]


In [ ]:
a.extend(b)
print(a)

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80]


In [ ]:
a=[1,2,4,7,2,2,8,9]
a.remove(2)
print(a)

[1, 4, 7, 2, 2, 8, 9]


In [ ]:
a.pop(2)
print(a)
a.pop()
print(a)

[1, 4, 2, 8, 9]
[1, 4, 2, 8]


In [ ]:
a.reverse()
print(a)

[8, 2, 4, 1]


In [ ]:
a=[1,2,4,7,2,2,8,9]
a.sort()
print(a)

[1, 2, 2, 2, 4, 7, 8, 9]


In [ ]:
a=list(range(0,10,2))
print(a)
b=a
print(b)
print(id(a))
print(id(b))
b.insert(10,5)
print(b)
print(a)
print(id(a))
print(id(b))

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
133118754404416
133118754404416
[0, 2, 4, 6, 8, 5]
[0, 2, 4, 6, 8, 5]
133118754404416
133118754404416


In [ ]:
a=list(range(0,10,2))
print(a)
b=a.copy()
print(b)
print(id(a))
print(id(b))
b.insert(10,5)
print(b)
print(a)
print(id(a))
print(id(b))

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
133118754393088
133118754394496
[0, 2, 4, 6, 8, 5]
[0, 2, 4, 6, 8]
133118754393088
133118754394496


In [ ]:
a=list(range(0,10,2))
print(a)
b=a[:]
print(b)
print(id(a))
print(id(b))
b.insert(10,5)
print(b)
print(a)
print(id(a))
print(id(b))

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]
133118755159488
133118755249408
[0, 2, 4, 6, 8, 5]
[0, 2, 4, 6, 8]
133118755159488
133118755249408


In [ ]:
c=a+b
print(c)

[0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 5]


In [ ]:
print(c*3)

[0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 5, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 5, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 5]


In [ ]:
print(10 in c)
print(8 in c)
print(10 not in c)

False
True
True


In [ ]:
a=list(range(0,41,4))
b=list(range(44,81,4))
l=b
print(a,l)
c=[0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40,l]
print(c[4])
print(c[11])

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40] [44, 48, 52, 56, 60, 64, 68, 72, 76, 80]
16
[44, 48, 52, 56, 60, 64, 68, 72, 76, 80]


In [ ]:
a=list(range(0,15))
print(type(a))
b=[]
for i in a:
  b.append(i*2)
print(b)

<class 'list'>
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]


In [ ]:
#tuple

In [ ]:
a=range(1,10)
print(type(a))
print(len(a))
print(a.count(4))
print(a.index(6))
print(sorted(a))
print(sorted(a,reverse=True))
print(min(a))
print(max(a))

<class 'range'>
9
1
5
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
1
9


In [ ]:
a=1
b=2
c=3
d=a,b,c
print(d)

(1, 2, 3)


In [ ]:
d=(1, 2, 3)
a,b,c=d
print(a,b,c)

1 2 3


In [ ]:
#set

In [ ]:
a={1,1,2,3,4,5,5,6,7,8,8,10}
print(a)

{1, 2, 3, 4, 5, 6, 7, 8, 10}


In [ ]:
b=set()
print(b)
print(type(a))

set()
<class 'set'>


In [ ]:
a={1,1,2,3,4,5,5,6,7,8,8,10}
a.add(11)
print(a)

{1, 2, 3, 4, 5, 6, 7, 8, 10, 11}


In [ ]:
a.update(a,range(11,21))
print(a)

{1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}


In [ ]:
a.pop()
print(a)

{2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}


In [ ]:
a.remove(4)
print(a)
a.remove(22)

{2, 3, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}


KeyError: 22

In [ ]:
a.discard(5)
print(a)
a.discard(22)

{2, 3, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}


In [ ]:
a.clear()
print(a)

set()


In [ ]:
#dictionary

In [ ]:
a=dict()
print(a)

{}


In [ ]:

a[1]='a'
a[2]='b'

In [ ]:
print(a)

{1: 'a', 2: 'b'}


In [ ]:
print(a[1])

a


In [ ]:
if 21 in a:
  print(a[21])
else:
  print('Not found')

Not found


In [ ]:
if 2 in a:
  print(a[2])
else:
  print('Not found')

b


In [ ]:
a[3]='Appy'
print(a)

{1: 'a', 2: 'b', 3: 'Appy'}


In [ ]:
a[2]='Python'
print(a)

{1: 'a', 2: 'Python', 3: 'Appy'}


In [ ]:
a[4]=a.pop(3)
print(a)

{1: 'a', 2: 'Python', 4: 'Appy'}


In [ ]:
dictionary= {1:'Apurvi',2:'Python',3:'Practice'}
del dictionary[3]
print(dictionary)


{1: 'Apurvi', 2: 'Python'}


In [ ]:
del dictionary

In [ ]:
a.clear()
print(a)

{}


In [ ]:
d=dict([(1,'ABC'),(2,'DFE'),(3,'GHI')])
print(d)

{1: 'ABC', 2: 'DFE', 3: 'GHI'}


In [ ]:
print(len(d))

3


In [ ]:
print(d.get(3))

GHI


In [ ]:
print(d.get(4))

None


In [ ]:
print(d.get(5,'Not Present'))

Not Present


In [ ]:
print(d.pop(1))

ABC


In [ ]:
print(d)

{2: 'DFE', 3: 'GHI'}


In [ ]:
print(d.popitem())

(3, 'GHI')


In [ ]:
print(d)

{2: 'DFE'}


dictionary= {1:'Apurvi',2:'Python',3:'Practice'}

In [ ]:
dic=dictionary.copy()
print(dic)

{1: 'Apurvi', 2: 'Python', 3: 'Practice'}


In [ ]:
print(dictionary.keys())

dict_keys([1, 2, 3])


In [ ]:
for i in dictionary.keys():
  print (i)

1
2
3


In [ ]:
print(dictionary.values())

dict_values(['Apurvi', 'Python', 'Practice'])


In [ ]:
for i in dictionary.values():
  print (i)

Apurvi
Python
Practice


In [ ]:
print(dictionary.items())

dict_items([(1, 'Apurvi'), (2, 'Python'), (3, 'Practice')])


In [ ]:
for i in dictionary.items():
  print (i)

(1, 'Apurvi')
(2, 'Python')
(3, 'Practice')


In [1]:
pip install numpy

In [2]:
#numerical python
#multidimensional array,matrices
#array - stirea multiple values in simple variable

In [4]:
import numpy as np
ar=np.array([1,2,3])
print(ar)

[1 2 3]


In [5]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
tr=np.array((1,2,3))
print(tr)

[1 2 3]


In [8]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
az=np.zeros((2,2))
print(az)

[[0. 0.]
 [0. 0.]]


In [12]:
azr=np.zeros((4,2))
print(azr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
ao=np.ones((2,3))
print(ao)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
aon=np.ones((4,3))
print(aon)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
ar=np.random.random((2,3))
print(ar)

[[0.6978254  0.7159076  0.35774348]
 [0.05431923 0.55069304 0.11538007]]


In [26]:
arn=np.arange(20,11,-1)
print(arn)

[20 19 18 17 16 15 14 13 12]


In [27]:
arn1=np.arange(20,25,1)
print(arn)

[20 19 18 17 16 15 14 13 12]


In [30]:
lin=np.linspace(2,6,7)
print(lin)

[2.         2.66666667 3.33333333 4.         4.66666667 5.33333333
 6.        ]


In [33]:
lin1=np.linspace(2,6,7,endpoint=False)
print(lin1)

[2.         2.57142857 3.14285714 3.71428571 4.28571429 4.85714286
 5.42857143]


In [34]:
lin2=np.linspace(2,6,7,retstep=True)
print(lin2)

(array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        ]), np.float64(0.6666666666666666))


In [37]:
lin3=np.linspace(2,6,7,dtype=None)
print(lin3)

[2.         2.66666667 3.33333333 4.         4.66666667 5.33333333
 6.        ]


In [41]:
lin4=np.linspace(2,6,6,axis=0)
print(lin4)

[2.  2.8 3.6 4.4 5.2 6. ]


In [43]:
lin5=lin4.reshape((2,3))
print(lin5)

[[2.  2.8 3.6]
 [4.4 5.2 6. ]]


In [45]:
f=lin5.flatten()
print(f)

[2.  2.8 3.6 4.4 5.2 6. ]


In [47]:
ar1=np.array([1+2j, 3+4j])
ar2=np.array(['2023-01-01', '2024-01-01'])
ar3=np.array([True, False, True])
ar4=np.array(['apple', 'banana', 'cherry'])
ar5=np.array([1.5, 2.5, 3.5])
ar6=np.array([1, 2, 3])

In [50]:
print(ar1.dtype)
print(ar2.dtype)
print(ar3.dtype)
print(ar5.dtype)
print(ar4.dtype)
print(ar6.dtype)

complex128
<U10
bool
float64
<U6
int64


In [51]:
ar2.ndim

1

In [52]:
az.ndim

2

In [53]:
ar2.size

2

In [54]:
az.size

4

In [55]:
ar2.itemsize

40

In [56]:
ar2.shape

(2,)

In [57]:
az.shape

(2, 2)

In [58]:
type(az)

numpy.ndarray

In [59]:
ar

array([[0.6978254 , 0.7159076 , 0.35774348],
       [0.05431923, 0.55069304, 0.11538007]])

In [60]:
art=ar.transpose()
print(art)

[[0.6978254  0.05431923]
 [0.7159076  0.55069304]
 [0.35774348 0.11538007]]


In [62]:
arr_1d = np.array([10, 20, 30, 40])
print(arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [66]:
arr_1d[1]

np.int64(20)

In [67]:
arr_2d[1,1]

np.int64(5)

In [68]:
arr_1d[1:3]

array([20, 30])

In [70]:
arr_2d[0:,1:]

array([[2, 3],
       [5, 6]])

In [71]:
arr_1d

array([10, 20, 30, 40])

In [72]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
arr_1d*5

array([ 50, 100, 150, 200])

In [74]:
arr_2d+2

array([[3, 4, 5],
       [6, 7, 8]])

In [75]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
print(arr_2d+arr_2d)

[[ 2  4  6]
 [ 8 10 12]]


In [77]:
print(arr_2d-arr_2d)

[[0 0 0]
 [0 0 0]]


In [78]:
print(arr_2d*arr_2d)

[[ 1  4  9]
 [16 25 36]]


In [79]:
print(arr_2d/arr_2d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [80]:
print(arr_2d%arr_2d)

[[0 0 0]
 [0 0 0]]


In [83]:
arr_2d.min()

np.int64(1)

In [84]:
arr_2d.max()

np.int64(6)

In [85]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.min(arr_2d,axis=0)

array([1, 2, 3])

In [87]:
np.min(arr_2d,axis=1)

array([1, 4])

In [88]:
np.max(arr_2d,axis=0)

array([4, 5, 6])

In [89]:
np.max(arr_2d,axis=1)

array([3, 6])

In [90]:
np.mean(arr_2d)

np.float64(3.5)

In [91]:
np.median(arr_2d)

np.float64(3.5)

In [92]:
np.average(arr_2d)

np.float64(3.5)

In [93]:
np.var(arr_2d)  #distance between data points

np.float64(2.9166666666666665)

In [94]:
np.std(arr_2d)  #distance from mean to data points

np.float64(1.707825127659933)